name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Features"
    labels:
      - "feature"
  - title: "Bug Fixes"
    labels:
      - "bug"
  - title: "Maintenance"
    labels:
      - "maintenance"
change-template: "- $TITLE #$NUMBER"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
include-labels:
  - "task"
  - "improvement"
  - "maintenance"
  - "bug"
  - "feature"
template: |
  ## What’s Changed

  $CHANGES
